PetStore/PetStore/Models/PaymentInformation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetStore.Models
{
    [Table("PaymentInformation")]
    public class PaymentInformation
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Credit Card Number is required.")]
        [Display(Name = "Credit card number")]
        [DataType(DataType.CreditCard)]
        [StringLength(16, ErrorMessage = "Enter a 16-digit credit card number.")]
        public string CardNumber { get; set; }

        [Required(ErrorMessage = "The month of expiration is required.")]
        [Display(Name = "Month")]
        public int ExpirationMonth { get; set; }

        [Required(ErrorMessage = "The year of expiration is required.")]
        [Display(Name = "Year")]
        public int ExpirationYear { get; set; }

        [Required(ErrorMessage = "The credit card pin is required.")]
        [Display(Name = "CCV")]
        [StringLength(3, ErrorMessage = "Enter a 3-digit pin.")]
        public string CardPin { get; set; }

        public Cart Cart
        {
            get
            {
                return (Cart)HttpContext.Current.Session["shoppingCart"];
            }
        }

        //public int[] Months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
        //public int[] Years = { 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030,
        //    2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038 };      
    }
}

PetStore/PetStore/Controllers/PaymentInformationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PetStore.Models;

namespace PetStore.Controllers
{
    public class PaymentInformationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PaymentInformations
        public ActionResult Index()
        {
            return View(db.PaymentInformation.ToList());
        }

        // GET: PaymentInformations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentInformation paymentInformation = db.PaymentInformation.Find(id);
            if (paymentInformation == null)
            {
                return HttpNotFound();
            }
            return View(paymentInformation);
        }

        // GET: PaymentInformations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PaymentInformations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CardNumber,ExpirationMonth,ExpirationYear,CardPin")] PaymentInformation paymentInformation)
        {
            if (ModelState.IsValid)
            {
                db.PaymentInformation.Add(paymentInformation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paymentInformation);
        }

        // GET: PaymentInformations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentInformation paymentInformation = db.PaymentInformation.Find(id);
            if (paymentInformation == null)
            {
                return HttpNotFound();
            }
            return View(paymentInformation);
        }

        // POST: PaymentInformations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CardNumber,ExpirationMonth,ExpirationYear,CardPin")] PaymentInformation paymentInformation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paymentInformation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paymentInformation);
        }

        // GET: PaymentInformations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PaymentInformation paymentInformation = db.PaymentInformation.Find(id);
            if (paymentInformation == null)
            {
                return HttpNotFound();
            }
            return View(paymentInformation);
        }

        // POST: PaymentInformations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PaymentInformation paymentInformation = db.PaymentInformation.Find(id);
            db.PaymentInformation.Remove(paymentInformation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PetStore/PetStore/Views/PaymentInformations/Create.cshtml
@model PetStore.Models.PaymentInformation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","PaymentInformations", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PaymentInformation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CardNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationMonth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardPin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardPin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardPin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Order" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetStore/PetStore/Views/PaymentInformations/Delete.cshtml
@model PetStore.Models.PaymentInformation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PaymentInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CardNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardPin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardPin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PetStore/PetStore/Views/PaymentInformations/Details.cshtml
@model PetStore.Models.PaymentInformation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PaymentInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CardNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardPin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardPin)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PetStore/PetStore/Views/PaymentInformations/Edit.cshtml
@model PetStore.Models.PaymentInformation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PaymentInformation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CardNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationMonth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardPin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardPin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardPin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetStore/PetStore/Views/PaymentInformations/Index.cshtml
@model IEnumerable<PetStore.Models.PaymentInformation>

@{
    ViewBag.Title = "Index";
}

<h2>Checkout</h2>

<!--<p>
    @Html.ActionLink("Create New", "Create")
</p>-->
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CardNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpirationMonth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpirationYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CardPin)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CardNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpirationMonth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpirationYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CardPin)
        </td>
 <!--       <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>-->
    </tr>
}

</table>